version: '3'

services:
  portfolio_db:
    container_name: portfolio_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=portfolio_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - app-net

  portfolio_api:
    container_name: portfolio_api
    image: portfolio:0.0.1-SNAPSHOT
    restart: always
    environment:
      - DATABASE_URL_SPRINGBOOT=jdbc:postgresql://portfolio_db:5432/portfolio_backend
    ports:
      - 80:8080
    depends_on:
      - portfolio_db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge