INSERT INTO stacks(portfolio_id, platform, name) VALUES(1, 1, 'Ruby');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(1, 1, 'Rails');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(1, 3, 'Heroku');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(2, 1, 'Next.js');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(2, 3, 'Netlify');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(3, 1, 'PHP');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(3, 2, 'MariaDB');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(3, 3, 'Nginx');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(3, 3, 'EC2');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(4, 1, 'Google Apps Script');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(4, 2, 'Google Spread Sheet');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(4, 2, 'Google Search Console');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(5, 1, 'Spring Security');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(5, 3, 'GitHub OAuth');
INSERT INTO stacks(portfolio_id, platform, name) VALUES(5, 3, 'OpenID');